name: genesis1
description: "A Flutter app for accessing and sharing past papers across universities."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  provider: ^6.1.1
  file_selector: ^1.0.1
  path_provider: ^2.1.2
  flutter_pdfview: ^1.3.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  http: ^1.1.2
  url_launcher: ^6.2.4
  syncfusion_flutter_pdfviewer: ^29.2.9
  share_plus: ^7.2.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
