// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAfaqlPTv5Jf1tr99TGJA-RyUttimtOw',
    appId: '1:744042005137:web:0c9c5dbc72fff26f203530',
    messagingSenderId: '744042005137',
    projectId: 'zzeeta',
    authDomain: 'zzeeta.firebaseapp.com',
    storageBucket: 'zzeeta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYYx8yw0PJQSyo2lMA_3PZDK5K_JhKFE',
    appId: '1:744042005137:android:83861a32369a3641203530',
    messagingSenderId: '744042005137',
    projectId: 'zzeeta',
    storageBucket: 'zzeeta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKzdNK1fyNkypey7zsizGpOeZsxwDdXo',
    appId: '1:744042005137:ios:31ed1128f8b5d499203530',
    messagingSenderId: '744042005137',
    projectId: 'zzeeta',
    storageBucket: 'zzeeta.firebasestorage.app',
    iosBundleId: 'com.example.genesis1',
  );

}